sudo: false
language: python
cache:
  pip: true
python:
  - '3.6'
install:
  - pip install tox-travis
script:
  - tox
deploy:
  provider: pypi
  user: mueslo
  password:
    secure: byGm5DSqoApb4r8lASCuc0+sq7FRQYzbVWR7Ya8cynJDBk08OLDlM6fskInpGFQqEUkXQRz9zTzE3d6Nf/LqsKpDrqLOeTSEVn7y8kxnV/4M3j0WHUL5OiyfILRiVOiPT6j81b4KFVblMDFmm2OcWznHL6AadInLVhkuZMtiZoSI21I8ES5pcHwX2HetcZaEpHKXqO4bI0oEGI6cuEh+hOTdRzPhpJnv+e0axNfc0SgKEHQnEemUovGDSOGPPCgq/1/7kYL508CreEHyZkPfmWBmT5vYItweILqhA3Bhty7kmLQgdGWn6c+wZf9eElLR1fCEz6HNZl8MfC3RX/PBvzkqgWuSpvdcDFlTSdezi2+jzD14FDQ56X/nrVtvCI9d2P7JT4TUydodKeea0WzM9UqGh9OsbODiwsOKTqcqmGHtcIT1ADLRVZSImMjOfl4fndi70Y5n7C1vdio5Q56fUQ/1hpgTOr///jqq6cjuznrvRSMxaRG7Lu20QsYnHfJc/68iWosBPky19Q8uPCKzqURraY0htdsUzSheKx3iYnjpPuN4p2I6obESkjPjpBMIzkqWnjKj9NCDZKnwlXXSThjqfcurSZW7nPDXg7M4EQJpyyqS5egJOCPsGHUyVEXLxxFwBoo+/Punjq5IGzfBSqt52iWevxPknZ6Jag7d8ag=
  on:
    tags: true
