name: Build wheels

on:  # uses a token, so never run on untrusted input (e.g. PRs)
  release:
    types: [published]
  push:
    branches:
      - test-build

jobs:
  build_sdist:
    name: Source distribution
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: python -m pip install build

      - name: Build source package
        run: python -m build

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
      BUILD_PLATFORM_INDEPENDENT: true
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            cibw_archs: "x86_64"
          #- os: ubuntu-latest  # Linux ARM requires emulation
          #  cibw_archs: "aarch64"
          - os: windows-latest
            cibw_archs: "x86_64"
          - os: macos-latest
            cibw_archs: "universal2"

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels for CPython 3.11
        uses: pypa/cibuildwheel@v2.12.3
        env:
          CIBW_BUILD: "cp311-*"
          CIBW_ARCHS: ${{ matrix.cibw_archs }}

      #- name: Build wheels for CPython 3.10
      #  uses: pypa/cibuildwheel@v2.12.3
      #  env:
      #    CIBW_BUILD: "cp310-*"
      #    CIBW_ARCHS: ${{ matrix.cibw_archs }}

      #- name: Build wheels for CPython 3.9
      #  uses: pypa/cibuildwheel@v2.12.3
      #  env:
      #    CIBW_BUILD: "cp39-*"
      #    CIBW_ARCHS: ${{ matrix.cibw_archs }}

      #- name: Build wheels for CPython 3.8
      #  uses: pypa/cibuildwheel@v2.12.3
      #  env:
      #    CIBW_BUILD: "cp38-*"
      #    CIBW_ARCHS: ${{ matrix.cibw_archs }}

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheelhouse/*.whl
          if-no-files-found: error
  publish_pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build_sdist, build_wheels]
    if: github.event_name == 'release'
    steps:
    - uses: actions/checkout@v3

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: dist

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@1.8
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_KEY }}