name: Run tests
on:
  push:
  pull_request:

jobs:
  test:
    name: test ${{ matrix.py_version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
          #- Windows
          #- MacOs
        py_version:
          - "3.10"
          - "3.9"
          - "3.8"
    steps:
      - name: Setup python for test ${{ matrix.py_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py_version }}
      - uses: actions/checkout@v2
      - name: Install tox
        run: python -m pip install tox tox-gh-actions
      - name: Run tox
        run: tox
